# nixpacks.toml
[phases.setup]
aptPkgs = [
    "build-essential",
    "python3-dev",
    "libldap2-dev",  # Para Debian/Ubuntu, este paquete provee las cabeceras de OpenLDAP
    "libsasl2-dev",  # A menudo requerido por python-ldap para la autenticación SASL
    "libssl-dev"     # Para dependencias de SSL/TLS
]

[start]
cmd = "odoo-bin --config=/app/odoo-arizon/odoo.conf --http-port=$PORT --http-interface=0.0.0.0 --without-demo=all --workers=2 --logfile=/dev/stdout" 