[options]
admin_passwd = Eitemm09*
db_name = railway
db_sslmode = prefer
addons_path = /app/addons,/app/odoo/addons
data_dir = ${RAILWAY_VOLUME_MOUNT_PATH}
http_interface = 0.0.0.0
proxy_mode = True
xmlrpc_interface = 0.0.0.0
longpolling_port = 0
workers = 0
max_cron_threads = 0
limit_memory_hard = 6442450944
limit_memory_soft = 4294967296
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
log_level = info
list_db = False
dbfilter = ^railway$
unaccent = False